# Generated by Django 2.2.1 on 2020-05-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_question_qid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit_Interested_Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.IntegerField()),
                ('name', models.CharField(max_length=256, null=True)),
                ('gender', models.CharField(max_length=256, null=True)),
                ('suburb', models.CharField(max_length=256, null=True)),
                ('country', models.CharField(max_length=256, null=True)),
                ('province', models.CharField(max_length=256, null=True)),
                ('email', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
